---
- name: Install K3s on control plane
  hosts: control_plane
  become: true
  vars:
    k3s_version: "v1.28.2+k3s1"  # Tilpas versionen hvis nødvendigt
    k3s_disable_components: "traefik"  # Liste over komponenter, der skal deaktiveres
  tasks:
    - name: Install K3s on master node (disable Traefik)
      shell: |
        curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --disable {{ k3s_disable_components }}
        echo "K3s installed on master node with Traefik disabled"
      args:
        warn: false

    - name: Retrieve K3s token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_data

    - name: Set K3s token fact
      set_fact:
        k3s_token: "{{ k3s_token_data['content'] | b64decode }}"

- name: Install K3s on worker nodes
  hosts: workers
  become: true
  vars:
    k3s_disable_components: "traefik"  # Ensartet deaktivering
  tasks:
    - name: Install K3s on worker node (disable Traefik)
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['control_plane']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['control_plane']['k3s_token'] }} sh -s - --disable {{ k3s_disable_components }}
        echo "K3s installed on worker node with Traefik disabled"
      args:
        warn: false
