---
- name: Test connection to Proxmox node
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: proxmox_server_ip
      prompt: "Enter the IP address or hostname of the Proxmox server"
      private: no

    - name: api_username
      prompt: "Enter your Proxmox username"
      private: no

    - name: api_password
      prompt: "Enter your Proxmox password"
      private: yes

  tasks:
    - name: Test connection
      proxmox_kvm:
        api_host: "{{ proxmox_server_ip }}"
        api_user: "{{ api_username }}"
        api_password: "{{ api_password }}"
        node: "localhost"
        state: query
      register: connection_test

    - name: Print connection test result
      debug:
        msg: "Connection test {{ 'succeeded' if connection_test.success else 'failed' }}"
