---
- name: Test SSH connection to Proxmox node
  hosts: localhost
  gather_facts: false

  vars:
    proxmox_server: localhost

  vars_prompt:
    - name: proxmox_ssh_user
      prompt: "Enter SSH username for Proxmox"
      private: no

    - name: proxmox_ssh_pass
      prompt: "Enter SSH password for Proxmox"
      private: yes

  tasks:
    - name: Attempt SSH connection to Proxmox node
      ansible.builtin.shell: sshpass -p {{ proxmox_ssh_pass }} ssh {{ proxmox_ssh_user }}@{{ proxmox_server }} hostname
      register: ssh_output
      ignore_errors: true

    - name: Print SSH connection status
      debug:
        msg: "SSH connection {{ 'successful' if ssh_output.rc == 0 else 'failed' }}"
