---
- name: Test SSH connection to Proxmox node
  hosts: localhost
  gather_facts: false

  vars:
    proxmox_server: localhost
    proxmox_ssh_user: root

  tasks:
    - name: Attempt SSH connection to Proxmox node
      ansible.builtin.shell: ssh {{ proxmox_ssh_user }}@{{ proxmox_server }} hostname
      register: ssh_output
      ignore_errors: true

    - name: Print SSH connection status
      debug:
        msg: "SSH connection {{ 'successful' if ssh_output.rc == 0 else 'failed' }}"
