---
- name: Check status of running VMs on Proxmox
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: proxmox_server_ip
      prompt: "Enter the IP address or hostname of the Proxmox server"
      private: no

    - name: api_username
      prompt: "Enter your Proxmox username"
      private: no

    - name: api_password
      prompt: "Enter your Proxmox password"
      private: yes

  tasks:
    - name: Get list of running VMs
      proxmox_kvm:
        api_host: "{{ proxmox_server_ip }}"
        api_user: "{{ api_username }}"
        api_password: "{{ api_password }}"
        node: "{{ 192.168.137.99 }}"
        state: query

      register: running_vms

    - name: Print status of running VMs
      debug:
        msg: "VM {{ item.name }} is {{ item.status }}"
      loop: "{{ running_vms.virtual_machines }}"
